org.gradle.jvmargs=-Xmx4G
minecraft_version=26.2
archives_base_name=reterraforged
mod_version=0.0.6
mod_id=reterraforged
maven_group=raccoonman.reterraforged
fabric_loader_version=0.19.3
fabric_api_version=0.155.2+26.2
neoforge_version=26.2.0.32-beta
terrablender_version=26.2.0.0.2
fabric.loom.disableObfuscation=true
