modLoader="javafml"
loaderVersion="[1,)"
license="MIT"

[[mixins]]
    config = "reterraforged-common.mixins.json"

[[mixins]]
    config = "reterraforged-neoforge.mixins.json"

[[accessTransformers]]
    file = "META-INF/accesstransformer.cfg"

[[mods]]
    modId="reterraforged"
    displayName="ReTerraForged"
    version="0.0.6"
    authors="dags,Won-Ton,raccoonman,Fhxa3"
    credits="dags,Won-Ton,raccoonman,Fhxa3"
    logoFile="logo.png"
    displayURL="https://github.com/Fhxa3/NeoTerraForged"
    issueTrackerURL="https://github.com/Fhxa3/NeoTerraForged/issues"
    description="A continuation of https://github.com/TerraForged/TerraForged"

[[dependencies.reterraforged]]
    modId="neoforge"
    mandatory=true
    versionRange="[26.1,26.2)"
    ordering="NONE"
    side="BOTH"

[[dependencies.reterraforged]]
	modId = "minecraft"
	mandatory = true
	versionRange = "[26.1,26.2)"
	ordering = "NONE"
	side = "BOTH"
